# https://github.com/ndmitchell/hlint
- flags:
  - default: false
- extensions:
  - default: false
- modules:
  - default: false
  - { name: Control.Monad, as: Monad }
  - { name: Data.Version, as: Version }
  - { name: Endo, as: Endo }
  - { name: Paths_endo, as: Package }
  - { name: System.Console.GetOpt, as: Console }
  - { name: System.Environment, as: Environment }
  - { name: System.Exit, as: Exit }
  - { name: System.IO, as: IO }
- functions:
  - default: true

- group: { name: dollar, enabled: true }
- group: { name: generalise, enabled: true }
