# https://github.com/ndmitchell/hlint
- flags:
  - default: false
- extensions:
  - default: false
- modules:
  - default: false
  - { name: Control.Monad, as: Monad }
  - { name: Data.Aeson, as: Aeson }
  - { name: Data.ByteString, as: Bytes }
  - { name: Data.ByteString.Base64, as: Base64 }
  - { name: Data.ByteString.Lazy, as: LazyBytes }
  - { name: Data.Int, as: Int }
  - { name: Data.Maybe, as: Maybe }
  - { name: Data.Text.Encoding, as: Encoding }
  - { name: Data.Version, as: Version }
  - { name: Endo, as: Endo }
  - { name: Paths_endo, as: Package }
  - { name: System.Console.GetOpt, as: Console }
  - { name: System.Clock, as: Clock }
  - { name: System.Environment, as: Environment }
  - { name: System.Exit, as: Exit }
  - { name: System.FilePath, as: FilePath }
  - { name: System.IO, as: IO }
  - { name: System.IO.Temp, as: Temp }
  - { name: System.Mem, as: Mem }
  - { name: Text.Printf, as: Printf }
- functions:
  - default: true

- group: { name: dollar, enabled: true }
- group: { name: generalise, enabled: true }
