# https://github.com/ndmitchell/hlint
- flags:
  - default: false
- extensions:
  - default: false
  - name: OverloadedStrings
- modules:
  - default: false
  - { name: Control.Monad, as: Monad }
  - { name: Data.Aeson, as: Aeson }
  - { name: Data.Aeson.Encoding, as: Aeson }
  - { name: Data.Aeson.Types, as: Aeson }
  - { name: Data.Binary, as: Binary }
  - { name: Data.Binary.Get, as: Binary }
  - { name: Data.Bits, as: Bits }
  - { name: Data.Bool, as: Bool }
  - { name: Data.ByteString, as: Bytes }
  - { name: Data.ByteString.Base64, as: Base64 }
  - { name: Data.ByteString.Builder, as: Builder }
  - { name: Data.ByteString.Char8, as: Latin1 }
  - { name: Data.ByteString.Lazy, as: LazyBytes }
  - { name: Data.Char, as: Char }
  - { name: Data.HashMap.Strict, as: HashMap }
  - { name: Data.Int, as: Int }
  - { name: Data.List, as: List }
  - { name: Data.Maybe, as: Maybe }
  - { name: Data.Text, as: Text }
  - { name: Data.Text.Encoding, as: Text }
  - { name: Data.Vector, as: Vector }
  - { name: Data.Version, as: Version }
  - { name: Data.Word, as: Word }
  - { name: Endo, as: Endo }
  - { name: Paths_endo, as: Package }
  - { name: System.Clock, as: Clock }
  - { name: System.Console.GetOpt, as: Console }
  - { name: System.Environment, as: Environment }
  - { name: System.Exit, as: Exit }
  - { name: System.FilePath, as: FilePath }
  - { name: System.IO, as: IO }
  - { name: System.IO.Temp, as: Temp }
  - { name: System.Mem, as: Mem }
  - { name: Text.Printf, as: Printf }
  - { name: Unsafe.Coerce, as: Unsafe }
- functions:
  - default: true

- group: { name: dollar, enabled: true }
- group: { name: generalise, enabled: true }
