# https://github.com/ndmitchell/hlint
- flags:
  - default: false
- extensions:
  - default: false
- modules:
  - default: false
  - { name: Control.Exception, as: Exception }
  - { name: Control.Monad, as: Monad }
  - { name: Data.ByteString, as: Bytes }
  - { name: Data.Int, as: Int }
  - { name: Data.Maybe, as: Maybe }
  - { name: Data.Version, as: Version }
  - { name: Endo, as: Endo }
  - { name: Paths_endo, as: Package }
  - { name: System.Console.GetOpt, as: Console }
  - { name: System.Environment, as: Environment }
  - { name: System.Exit, as: Exit }
  - { name: System.FilePath, as: FilePath }
  - { name: System.IO, as: IO }
  - { name: System.Mem, as: Mem }
- functions:
  - default: true

- group: { name: dollar, enabled: true }
- group: { name: generalise, enabled: true }
