# https://github.com/ndmitchell/hlint
- flags:
  - default: false
- extensions:
  - default: false
  - name: OverloadedStrings
- modules:
  - default: true
- functions:
  - default: true

- group: { name: dollar, enabled: true }
- group: { name: generalise, enabled: true }
