# https://github.com/sol/hpack
name: endo
version: 0.0.0

category: Game
description: Endo parses and generates Rocket League replays.
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: Parse and generate Rocket League replays.

dependencies:
  base: '>= 4.11.1 && < 4.12'
ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-missing-exported-signatures # https://ghc.haskell.org/trac/ghc/ticket/14794
  - -Wno-safe

library:
  source-dirs: library

executable:
  dependencies: endo
  ghc-options:
    - -rtsopts
    - -threaded
  main: Main.hs
  source-dirs: executables

tests:
  test:
    dependencies: endo
    main: Main.hs
    source-dirs: executables
