# https://github.com/sol/hpack
name: endo
version: 0.0.0

category: Game
description: Endo parses and generates Rocket League replays.
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: Parse and generate Rocket League replays.

dependencies:
  aeson: '>= 1.3.1 && < 1.4'
  base64-bytestring: '>= 1.0.0 && < 1.1'
  base: '>= 4.11.1 && < 4.12'
  binary: '>= 0.8.5 && < 0.9'
  bytestring: '>= 0.10.8 && < 0.11'
  text: '>= 1.2.3 && < 1.3'
ghc-options:
  - -Weverything
  - -Wno-all-missed-specializations
  - -Wno-implicit-prelude
  - -Wno-missing-exported-signatures # https://ghc.haskell.org/trac/ghc/ticket/14794
  - -Wno-safe
  - -Wno-unsafe

library:
  source-dirs: library

executable:
  dependencies: endo
  ghc-options:
    - -rtsopts
    - -threaded
  main: Main.hs
  other-modules: []
  source-dirs: executables

tests:
  test:
    dependencies:
      clock: '>= 0.7.2 && < 0.8'
      endo: null
      filepath: '>= 1.4.2 && < 1.5'
      temporary: '>= 1.3 && < 1.4'
    ghc-options:
      - -rtsopts
      - -threaded
    main: Main.hs
    other-modules: []
    source-dirs: tests
